[package]
name = "tictactoe"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tictactoe"
path = "src/ui.rs"

[dependencies]
chrono = "0.4.41"
crossterm = "0.29.0"
tokio = { version = "1", features = ["full"] }
